server:
  port: 8090
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:

  #H2
  h2:
    console:
      enabled: true

  output:
    ansi:
      enabled: always

  datasource: 
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    
#MariaDB
#  datasource: 
#    url: jdbc:mariadb://localhost:3306/test
#    username: sungho
#    password: 1234


#JPA
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 10

#쿼리 파라미터 출력
logging:
  level:
    org.hibernate.type: trace