server:
  port: 8091
  servlet:    context-path: /
    
spring:


#H2
  h2:
    console:
      enabled: true
      
  datasource:     url: jdbc:h2:tcp://localhost/~/test
    username: sa
    
#MariaDB
#  datasource: #    url: jdbc:mariadb://localhost:3306/test
#    username: sungho
#    password: 1234


#JPA
  jpa:
    show-sql: true 
    
    properties:
      hibernate:
        ddl.auto: create
        dialect: org.hibernate.dialect.H2Dialect
        show-sql: true
        format_sql: true
        use_sql_comments: true
        jdbc:
        batch_size: 10 